#!/usr/bin/env node
/**
 * `THIRD-PARTY-NOTICES.md` (AXIOMAP.md §7, Phase 9).
 *
 * Phase 9 owns the file's place in the release; this generator and the
 * packaging step that includes it are Phase 8b's, because 8b is the phase that
 * builds the first artifact which actually **redistributes** anything. §7 names
 * the two vectors — the `.vsix` and `export --format html` — and adds a third
 * destination for the file itself, the npm tarball, since installing an MIT CLI
 * puts elkjs on somebody's disk.
 *
 * Attribution is not paperwork here. `elkjs` is `EPL-2.0 OR GPL-3.0-or-later`,
 * the `.vsix` ships its worker source verbatim, and EPL-2.0 §3 requires the
 * notice to travel with it. Shipping the package without this file would be
 * shipping a licence violation, which is why the packaging step refuses to.
 *
 * ### Generated, not written
 *
 * The same walk `check-licences.mjs` does — one source of truth for what is in
 * the production tree — plus each package's own licence text where it ships one.
 * Verbatim text rather than a link: a notice that requires network access to
 * read is not a notice, and decision #2 is that this tool never needs the
 * network.
 *
 * Usage:
 *   node scripts/notices.mjs           # write THIRD-PARTY-NOTICES.md
 *   node scripts/notices.mjs --check   # fail if the file is not what this would write
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { declaredLicence } from './check-licences.mjs';

const REPO_ROOT = resolve(import.meta.dirname, '..');
export const NOTICES_FILE = join(REPO_ROOT, 'THIRD-PARTY-NOTICES.md');

/** `LICENSE`, `LICENCE`, `LICENSE.md`, `COPYING`, … whatever the package used. */
function licenceText(dir) {
  let entries;
  try {
    entries = readdirSync(dir);
  } catch {
    return null;
  }
  const named = entries
    .filter((name) => /^(licen[cs]e|copying|notice)(\.|$)/i.test(name))
    .sort();
  for (const name of named) {
    try {
      const text = readFileSync(join(dir, name), 'utf8').trim();
      if (text !== '') return text;
    } catch {
      // A directory named LICENSE, or an unreadable one. Try the next.
    }
  }
  return null;
}

/**
 * The production tree, with each package's licence text.
 *
 * Deliberately a second walk rather than a change to `productionDependencies`:
 * that function is the licence *gate's*, it runs in CI on every push, and it has
 * no reason to read a few hundred licence files.
 */
export function noticeEntries() {
  const raw = execFileSync(
    'pnpm',
    ['list', '--recursive', '--prod', '--depth', 'Infinity', '--json'],
    { cwd: REPO_ROOT, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 },
  );

  const found = new Map();
  const visit = (deps) => {
    for (const [name, dep] of Object.entries(deps ?? {})) {
      if (!dep?.path) continue;
      // This repo's own packages are MIT and covered by LICENSE.
      if (dep.path.startsWith(join(REPO_ROOT, 'packages'))) {
        visit(dep.dependencies);
        continue;
      }
      const key = `${name}@${String(dep.version ?? '')}`;
      if (!found.has(key)) {
        let manifest = {};
        try {
          manifest = JSON.parse(readFileSync(join(dep.path, 'package.json'), 'utf8'));
        } catch {
          // Handled as "no declared licence" below, and by the licence gate.
        }
        found.set(key, {
          name,
          version: String(dep.version ?? ''),
          licence: declaredLicence(manifest) || '(none declared)',
          text: licenceText(dep.path),
        });
      }
      visit(dep.dependencies);
    }
  };

  for (const project of JSON.parse(raw)) visit(project.dependencies);
  return [...found.values()].sort(
    (a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version),
  );
}

export function renderNotices(entries) {
  const lines = [
    '# Third-party notices',
    '',
    'Axiomap is MIT licensed (see `LICENSE`). It redistributes the packages below,',
    'each under its own terms. This file is generated by `node scripts/notices.mjs`',
    'from the production dependency tree; do not edit it by hand.',
    '',
    'It travels with every artifact that carries third-party code: the `.vsix`, the',
    'npm tarballs, and — for the one package whose source is inlined into it — the',
    'footer of `axiomap export --format html`.',
    '',
    '## elkjs',
    '',
    '`elkjs` is dual licensed `EPL-2.0 OR GPL-3.0-or-later`, and Axiomap takes the',
    'EPL-2.0 arm. Two artifacts contain its source rather than merely depending on',
    'it: the `.vsix`, which ships `elk-worker.min.js` so the layout can run in a',
    'worker (§9 rule 6), and the self-contained HTML export, which inlines the same',
    'file. Its notice and licence text are in the list below with the rest.',
    '',
    `## Packages (${String(entries.length)})`,
    '',
  ];

  for (const entry of entries) {
    lines.push(`- ${entry.name}@${entry.version} — ${entry.licence}`);
  }
  lines.push('');
  lines.push('---');
  lines.push('');

  for (const entry of entries) {
    lines.push(`### ${entry.name}@${entry.version}`);
    lines.push('');
    lines.push(`Licence: ${entry.licence}`);
    lines.push('');
    if (entry.text === null) {
      lines.push(
        'No licence file ships in this package; the terms above are the ones it declares.',
      );
    } else {
      lines.push('```');
      // A fenced block ends at the first ``` at line start, so any inside it
      // would truncate the notice it is supposed to reproduce verbatim.
      lines.push(entry.text.replace(/^```/gm, ' ```'));
      lines.push('```');
    }
    lines.push('');
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

function main() {
  const content = renderNotices(noticeEntries());

  if (process.argv.includes('--check')) {
    let current = '';
    try {
      current = readFileSync(NOTICES_FILE, 'utf8');
    } catch {
      console.error('THIRD-PARTY-NOTICES.md is missing. Run: node scripts/notices.mjs');
      process.exit(1);
    }
    if (current !== content) {
      console.error(
        'THIRD-PARTY-NOTICES.md is out of date with the production dependency tree.\n' +
          'Run: node scripts/notices.mjs',
      );
      process.exit(1);
    }
    console.log('THIRD-PARTY-NOTICES.md is up to date.');
    return;
  }

  writeFileSync(NOTICES_FILE, content);
  console.log(`Wrote THIRD-PARTY-NOTICES.md — ${String(noticeEntries().length)} packages.`);
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
